version: "3.8"

services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/data
    command:
      - --host=0.0.0.0
      - --port=8545

      # Apenas mnemonic (determin√≠stico automaticamente)
      - --wallet.mnemonic=minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef

      # Persistir DB
      - --database.dbPath=/data

      # Chain ID fixo
      - --chain.chainId=5777

      # Debug logs
      - --logging.debug=true
