version: "3.8"

services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/data
    command:
      - --host=0.0.0.0
      - --port=8545

      - --wallet.mnemonic=minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef


      - --database.dbPath=/data

      - --chain.chainId=5777

      - --logging.debug=true
